"""Markdown reports generated from results directories. Nothing in them is typed by hand."""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

import pandas as pd

from vizor.optimize.sensitivity import position_robustness, sensitivity

README_START = "<!-- results:start (generated by `vizor report`, do not edit) -->"
README_END = "<!-- results:end -->"


METRIC_NAMES = {
    "imp_pwc": "PAWC share",
    "c_share": "citation share (C-SoV, share of the answer's valid markers)",
    "mentioned": "brand-mention rate (answers that name the target brand)",
}


def _sha(text: str) -> str:
    import hashlib

    return hashlib.sha256(text.encode()).hexdigest()[:12]


def _f(x, digits: int = 1, sign: bool = False) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:+.{digits}f}" if sign else f"{x:.{digits}f}"


def _ci(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits, True)} [{_f(lo, digits, True)}, {_f(hi, digits, True)}]"


def _lvl(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits)} [{_f(lo, digits)}, {_f(hi, digits)}]"


def _p(p) -> str:
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    return "<0.001" if p < 0.001 else f"{p:.3f}"


def _table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _read(d: Path, name: str) -> pd.DataFrame | None:
    p = d / name
    return pd.read_csv(p) if p.exists() else None


def load(d: Path) -> dict:
    from vizor.inspect import recompute_rows

    manifest = json.loads((d / "manifest.json").read_text())
    if manifest.get("input_fingerprints_match") is False:
        invalid = (
            "Source or corpus changed during this run; its comparisons have invalid provenance."
        )
    else:
        matches, _ = recompute_rows(d)
        invalid = (
            None
            if matches
            else "Stored answers or attribution rows do not match the current parser; "
            "these comparisons are archival."
        )
    return {
        "dir": d,
        "manifest": manifest,
        "invalid_reason": invalid,
        "domains": _read(d, "baseline_domains.csv"),
        "deltas": _read(d, "deltas.csv"),
        "decomposition": _read(d, "decomposition.csv"),
        "position": _read(d, "position_sweep.csv"),
        "boost": _read(d, "boost_sweep.csv"),
        "bandit": _read(d, "bandit_summary.csv"),
        "trajectory": _read(d, "trajectory.csv"),
        "sampled_primary": load_sampled_primary(d),
    }


def load_sampled_primary(d: Path) -> dict | None:
    """Study 2's fallback primary (scripts/sampled_primary.py), when the run has one. Its rule
    replaces the legacy Holm Wilcoxon in deltas.csv for the verdict."""
    p = d / "sampled_primary.json"
    return json.loads(p.read_text()) if p.exists() else None


GATE_CRITERIA = {
    "1_slot_detected": "1",
    "2_faq_negative": "2",
    "3_ci_narrower": "3",
    "4_spearman": "4",
}


def sampled_rule_md(sp: dict) -> str:
    """One sentence on why and how the sampled primary decides."""
    g = sp.get("gate")
    why = ""
    if g and not g["passed"]:
        crit = " and ".join(GATE_CRITERIA.get(c, c) for c in g["failed"])
        why = f"AP failed its validation gate on criteria {crit}, so "
    return (
        f"{why}the primary is the sampled citation share (C-SoV) on {sp['arms'][0]['n_pages']} "
        "page units: an arm has an effect (`*`) when the exact Wilcoxon and the sign-flip p are "
        f"both below 0.05 after Holm over the {len(sp['family'])} arms."
    )


def label(r: dict) -> str:
    m = r["manifest"]
    if m.get("llm_is_fake"):
        return "FakeLLM (pipeline check)"
    name = m["config"].get("label")
    if name:
        return name
    if m["config"]["llm"]["backend"] == "ollama":
        return f"{m['llm_model']} via Ollama (small local model, reduced design)"
    return m["llm_model"]


def header_md(r: dict) -> str:
    m = r["manifest"]
    usage = m.get("llm_usage") or {}
    lines = [
        f"- Results: `{r['dir'].as_posix()}` (git {m.get('git_commit')}, {m.get('started', '')[:10]})",
        f"- Answer model: `{m['llm_model']}`"
        + (
            " (deterministic extractive stand-in; pipeline check, not model evidence)"
            if m.get("llm_is_fake")
            else ""
        ),
        f"- Retrieval: `{m['embedder_id']}` + `{m['reranker_id']}`, index `{m.get('index_backend')}`",
        f"- Sentiment: `{m['sentiment_backend']}`; PAWC decay: {m['decay']}",
        f"- {m['n_queries']} queries x {m['samples']} samples, {m['n_docs']} pages",
    ]
    backend = m["config"]["llm"]["backend"]
    meta = m["config"]["llm"].get("server_meta") or {}
    if meta:
        lines.append(
            "- Served by "
            + ", ".join(f"{k} `{v}`" for k, v in meta.items())
            + f" at `{m['config']['llm'].get('base_url')}`"
        )
    if m.get("system_prompt"):
        sp = m["system_prompt"]
        lines.append(
            f"- System message (sha256 `{_sha(sp)}`, full text in the manifest): "
            f"“{sp[:90].rstrip()}…”"
        )
    if m.get("primary_metric"):
        lines.append(f"- Primary metric for the verdict: {METRIC_NAMES[m['primary_metric']]}")
    if usage and backend in ("ollama", "openai_compat"):
        lines.append(
            f"- Local calls: {usage.get('calls', 0)} new, {usage.get('cache_hits', 0)} cached (no API spend)"
        )
    elif usage:
        lines.append(
            f"- API calls: {usage.get('calls', 0)} new, {usage.get('cache_hits', 0)} cached; "
            f"estimated spend ${usage.get('spent_usd', 0):.2f} (list prices)"
        )
    if m.get("skipped_due_to_budget"):
        lines.append(f"- Skipped (budget cap reached): {', '.join(m['skipped_due_to_budget'])}")
    return "\n".join(lines)


def domains_md(r: dict) -> str:
    df = r["domains"]
    has_mentions = "mention_rate" in df.columns
    rows = [
        [
            f"{x.domain}{' (target)' if x.role == 'target' else ''}",
            _f(x.retrieval_rate * 100, 0),
            _f(x.citation_rate * 100, 0),
            _f(x.conversion * 100, 0),
            _f(x.c_sov * 100),
            _f(x.pawc_sov * 100),
            _f(x.first_cite_sentence, 2),
            _f(x.ignored_rate * 100, 0),
            _f(x.answer_sentiment, 2, True),
            *(
                [
                    _f(x.mention_rate * 100, 0),
                    _f(x.mentioned_not_cited_rate * 100, 0),
                    _f(x.cited_not_mentioned_rate * 100, 0),
                ]
                if has_mentions
                else []
            ),
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Domain",
            "Retrieved %",
            "Cited %",
            "Cited when retrieved %",
            "Pooled marker share %",
            "PAWC share %",
            "First cite (sentence)",
            "Ignored when retrieved %",
            "Answer sentiment",
            *(["Named %", "Named, not cited %", "Cited, not named %"] if has_mentions else []),
        ],
        rows,
    )


def _verdict(x, col: str, sig: str, ctrl) -> str:
    if x.arm in ctrl:
        return "control"
    p = getattr(x, col, float("nan"))
    return _p(p) + (" *" if bool(getattr(x, sig, False)) and not pd.isna(p) else "")


def deltas_md(r: dict) -> str:
    df = r["deltas"]
    if "p_mention" in df.columns:
        return deltas_md_v2(r)
    return deltas_md_v1(r)


def deltas_md_v2(r: dict) -> str:
    """Arms table for runs with a primary metric, mentions and format diagnostics."""
    df = r["deltas"]
    ctrl = ("noop", "aa_resample")
    primary = df["primary"].iloc[0]
    head = {"c_share": "ΔC-SoV", "imp_pwc": "ΔPAWC", "mentioned": "Δnamed"}
    cols = {
        "c_share": ("d_csov_pp", "d_csov_lo", "d_csov_hi"),
        "imp_pwc": ("d_pwc_pp", "d_pwc_lo", "d_pwc_hi"),
        "mentioned": ("d_mention_pp", "d_mention_lo", "d_mention_hi"),
    }
    order = [primary] + [m for m in ("c_share", "imp_pwc", "mentioned") if m != primary]
    sp = r.get("sampled_primary") if primary == "c_share" else None
    sp_rows = {x["arm"]: x for x in (sp["arms"] + sp["controls"])} if sp else {}
    rows = []
    for x in df.itertuples():
        cells = [f"`{x.arm}`"]
        s_ = sp_rows.get(x.arm)
        for m in order:
            a, lo, hi = cols[m]
            if s_ and m == "c_share":
                cells.append(_ci(s_["d_c_share_pp"], s_["lo"], s_["hi"]))
            else:
                cells.append(_ci(getattr(x, a), getattr(x, lo), getattr(x, hi)))
        if sp:
            if x.arm in ctrl or not s_:
                rule = "control"
            else:
                rule = f"{_p(s_['p_wilcoxon_holm'])} / {_p(s_['p_perm_holm'])}" + (
                    " *" if s_["significant"] else ""
                )
            cells += [rule, "control" if x.arm in ctrl else _p(x.p_holm)]
        else:
            cells.append(_verdict(x, "p_holm", "significant", ctrl))
        n_units = s_["n_pages"] if s_ else int(x.n_units)
        cells += [
            _verdict(x, "p_mention_holm", "mention_significant", ctrl),
            f"{int(x.n_sources_changed)}" if x.kind == "doc" else "",
            _f(x.uncited_rate_pct, 0),
            _f(x.unparsed_rate_pct, 1),
            _f(x.last_only_rate_pct, 0),
            f"{int(x.n_queries)} / {n_units}",
        ]
        rows.append(cells)
    verdict_cols = (
        [
            "p (Holm, primary: Wilcoxon / sign-flip)",
            "Study 1 test (continuity, not the Study 2 rule)",
        ]
        if sp
        else ["p (Holm, primary)"]
    )
    header = (
        ["Arm"]
        + [f"{head[m]} pp [95% CI]" + (" (primary)" if m == primary else "") for m in order]
        + verdict_cols
        + [
            "p (Holm, named)",
            "Queries whose sources changed",
            "Uncited %",
            "Unparsed markers %",
            "Cites only on last sentence %",
            "n",
        ]
    )
    fams = sorted(set(df.loc[~df.arm.isin(ctrl), "family"])) if "family" in df else ["arms"]
    if sp:
        verdict = (
            "The verdict follows `sampled_primary.json`: "
            + sampled_rule_md(sp)
            + " The ΔC-SoV column, its intervals and the `n` units come from that file (page "
            "units, A/A included; the A/A's ΔPAWC and Δnamed stay on its query units). The Study 1 column is the Holm-adjusted Wilcoxon (zero_method "
            "zsplit) that decided Study 1; it is shown for continuity and decides nothing here. "
        )
    else:
        verdict = (
            "The verdict is the Holm-adjusted Wilcoxon p on the primary metric "
            f"({METRIC_NAMES[primary]}), below 0.05 (`*`). "
        )
    note = (
        verdict + "The brand-mention test (“named”: the answer names the target brand, with or "
        "without a citation) gets its own Holm adjustment. "
        + (
            "Content-only arms (`content:`) keep the baseline's sources and their order and change only the "
            "edited page's text; they form a separate Holm family. "
            if "content" in fams
            else ""
        )
        + "`noop` and `aa_resample` are controls outside every family. Page arms are tested on edited-page "
        "units (queries sharing an edited page are not independent); `n` is queries / units. The 95% CIs "
        "resample those units and are descriptive. The last four columns describe the arm's answers: "
        "no valid citation at all, citation-like text the parser could not map to a source, and every "
        "citation collected on the final sentence (for those answers PAWC's position weighting is "
        "meaningless). “Queries whose sources changed” counts queries where the arm changed the list "
        "of sources the model saw."
    )
    return note + "\n\n" + _table(header, rows)


def decomposition_md(r: dict) -> str:
    df = r.get("decomposition")
    if df is None or not len(df):
        return ""
    primary = df["primary"].iloc[0]
    key = {"c_share": "csov", "imp_pwc": "pwc", "mentioned": "mention"}[primary]

    def g(x, lab: str, m: str) -> str:
        return _ci(
            getattr(x, f"{lab}_{m}_pp"), getattr(x, f"{lab}_{m}_lo"), getattr(x, f"{lab}_{m}_hi")
        )

    rows = []
    for x in df.itertuples():
        rows.append(
            [
                f"`{x.arm}`",
                g(x, "total", key),
                g(x, "content", key),
                g(x, "rank", key) + f" (p {_p(x.rank_p)})",
                g(x, "total", "mention"),
                g(x, "content", "mention"),
                g(x, "rank", "mention"),
                str(int(x.n_sources_changed)),
            ]
        )
    name = {"csov": "ΔC-SoV", "pwc": "ΔPAWC", "mention": "Δnamed"}[key]
    return (
        "Each page edit split into what the new text did with the same sources in the same order "
        "(content-only arm) and what it did by changing retrieval (full arm minus content-only arm, "
        "paired per query). Total = content + rank-mediated. The p next to the rank-mediated effect "
        "is an unadjusted Wilcoxon on page units.\n\n"
        + _table(
            [
                "Page edit",
                f"Total {name} pp",
                f"Content-only {name} pp",
                f"Rank-mediated {name} pp",
                "Total Δnamed pp",
                "Content-only Δnamed pp",
                "Rank-mediated Δnamed pp",
                "Queries whose sources changed",
            ],
            rows,
        )
    )


def deltas_md_v1(r: dict) -> str:
    df = r["deltas"]
    ctrl = ("noop", "aa_resample")
    rows = [
        [
            f"`{x.arm}`",
            _ci(x.d_pwc_pp, x.d_pwc_lo, x.d_pwc_hi),
            _f(x.rel_pct, 0, True) if not pd.isna(x.rel_pct) else "n/a",
            _ci(x.d_csov_pp, x.d_csov_lo, x.d_csov_hi),
            _f(x.d_cite_rate_pp, 1, True),
            _f(getattr(x, "d_pwc_given_cited_pp", float("nan")), 1, True),
            _f(getattr(x, "uncited_rate_pct", float("nan")), 0),
            _f(x.d_sentiment, 3, True),
            _p(x.p_holm) + (" *" if getattr(x, "significant", False) else "")
            if x.arm not in ctrl
            else "control",
            f"{int(x.n_queries)} / {int(getattr(x, 'n_units', x.n_queries))}",
        ]
        for x in df.itertuples()
    ]
    note = (
        "An arm counts as having an effect when its Holm-adjusted Wilcoxon p-value is below "
        "0.05 (`*`). The 95% confidence intervals are descriptive. `noop` and `aa_resample` are "
        "controls and are excluded from the Holm family. Page arms change each query's focus page. "
        "They are tested across (fold, page) units because queries that share an edited page are "
        "not independent; `n` reports queries / units. Arms that use the tracked queries are "
        "cross-fitted: built on one half of the queries and scored on the other. "
        '"ΔPAWC if cited" counts only answers with citations. Citation-format failures instead '
        "appear in the uncited rate."
    )
    return (
        note
        + "\n\n"
        + _table(
            [
                "Arm",
                "ΔPAWC pp [95% CI]",
                "Rel Δ %",
                "ΔC-SoV pp [95% CI]",
                "Δ cited pp",
                "ΔPAWC if cited pp",
                "Uncited answers %",
                "Δ sentiment",
                "p (Holm)",
                "n",
            ],
            rows,
        )
    )


def position_md(r: dict) -> str:
    df = r["position"]
    csov = "primary" in df.columns and df["primary"].iloc[0] == "c_share"
    first = df.position.iloc[0]
    rows = []
    for x in df.itertuples():
        ref = x.position == first
        d = (
            _ci(x.d_csov_vs_first_pp, x.d_csov_lo, x.d_csov_hi)
            if csov
            else _ci(x.d_pwc_vs_first_pp, x.d_lo, x.d_hi)
        )
        rows.append(
            [
                str(int(x.position)),
                *([_f(x.c_share_pct)] if csov else []),
                _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
                "ref" if ref else d,
                _f(x.cite_rate_pct, 0),
                (_p(x.p_holm) + (" *" if _sig(x) else ""))
                if not ref and hasattr(x, "p_holm")
                else "",
                str(int(x.n_queries)),
            ]
        )
    return _table(
        [
            "Target slot",
            *(["C-SoV %"] if csov else []),
            "PAWC share % [95% CI]",
            f"Δ{'C-SoV' if csov else 'PAWC'} vs slot 1 pp [95% CI]",
            "Cited %",
            "p (Holm, sweeps)",
            "n",
        ],
        rows,
    )


def boost_md(r: dict) -> str:
    df = r["boost"]
    rows = [
        [
            _f(x.boost, 2),
            _f(x.retrieval_pct, 0),
            _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi) if x.boost != 0 else "ref",
            _f(x.cite_rate_pct, 0),
            (_p(x.p_holm) + (" *" if _sig(x) else ""))
            if x.boost != 0 and hasattr(x, "p_holm")
            else "",
            _cls(x, "set_changed") if x.boost != 0 else "",
            _cls(x, "order_only") if x.boost != 0 else "",
            _cls(x, "unchanged") if x.boost != 0 else "",
        ]
        for x in df.itertuples()
    ]
    return (
        "For each query, these classes compare the boosted source list with w=0: a different set "
        "of sources, the same sources in a different order, or no change. Each cell shows "
        "`n queries: mean ΔPAWC pp`.\n\n"
        + _table(
            [
                "Boost w",
                "Target retrieved %",
                "PAWC share % [95% CI]",
                "Δ vs w=0 pp [95% CI]",
                "Cited %",
                "p (Holm, sweeps)",
                "Set changed",
                "Order only",
                "Unchanged",
            ],
            rows,
        )
    )


def _cls(x, c: str) -> str:
    n = getattr(x, f"n_{c}", None)
    if n is None or (isinstance(n, float) and math.isnan(n)):
        return ""
    d = getattr(x, f"d_pwc_{c}_pp")
    return f"{int(n)}: {_f(d, 1, True)}" if n else "0"


def _sig(x) -> bool:
    return bool(getattr(x, "significant", False)) and not pd.isna(
        getattr(x, "p_holm", float("nan"))
    )


def claim_md(r: dict) -> str:
    """What the sweeps and arms measured, stated only through the Holm verdict rule and the MDE."""
    m, pos, boost, deltas = r["manifest"], r["position"], r["boost"], r["deltas"]
    if m.get("llm_is_fake"):
        return (
            f"- FakeLLM applies an explicit −{m.get('fake_llm_position_prior') or 0.05:g} per-slot position "
            "penalty; this sweep recovers that built-in prior and is not evidence about real models."
        )
    out = []
    if pos is not None and len(pos) > 1:
        primary = str(pos.primary.iloc[0]) if "primary" in pos else "imp_pwc"
        is_csov = primary == "c_share"
        metric_name = "C-SoV" if is_csov else "PAWC share"
        slots = ", ".join(
            f"slot {int(x.position)} {_f(x.c_share_pct if is_csov else x.pwc_pct)}%"
            for x in pos.itertuples()
        )
        sig = [x for x in pos.iloc[1:].itertuples() if _sig(x)]
        if sig:
            detail = "; ".join(
                f"slot {int(x.position)} vs 1: "
                + (
                    _ci(x.d_csov_vs_first_pp, x.d_csov_lo, x.d_csov_hi)
                    if is_csov
                    else _ci(x.d_pwc_vs_first_pp, x.d_lo, x.d_hi)
                )
                + f" pp (Holm p {_p(x.p_holm)})"
                for x in sig
            )
            verdict = f"Holm-significant differences: {detail}."
        else:
            verdict = "No slot differs from slot 1 under the Holm rule."
        out.append(
            f"- Context order (same pages, target forced into each slot, n={int(pos.n_queries.iloc[0])} queries): "
            f"{metric_name} {slots}. {verdict}"
        )
        rob = position_robustness(r["dir"])
        if rob:
            pages = ", ".join(f"{k} {_f(v, 1, True)}" for k, v in rob["per_page_delta_pp"].items())
            out.append(
                f"- How fragile the slot {rob['last_slot']} result is: its raw p is {_p(rob['raw_p'])} over "
                f"{rob['n_queries']} queries, but those queries are served by only {rob['n_pages']} target pages. "
                f"Per page, slot {rob['last_slot']} minus slot {rob['first_slot']} on {metric_name} is {pages} pp, and a Wilcoxon "
                f"test on the page means gives p = {_p(rob['page_level_p'])}. It also depends on the sweeps "
                f"forming their own Holm family: in one family with the arms ({rob['joint_family_size']} tests) "
                f"its Holm p would be {_p(rob['joint_holm_p'])}."
            )
    if boost is not None and len(boost) > 1:
        ss = m.get("score_scale", {})
        parts = []
        base_ret = boost.iloc[0].retrieval_pct
        for x in boost.iloc[1:].itertuples():
            ret = (
                f"target retrieval unchanged at {_f(x.retrieval_pct, 0)}%"
                if abs(x.retrieval_pct - base_ret) < 1e-9
                else f"target retrieval {_f(base_ret, 0)}% → {_f(x.retrieval_pct, 0)}%"
            )
            parts.append(
                f"w={_f(x.boost, 2)}: {ret}, ΔPAWC {_ci(x.d_pwc_pp, x.d_lo, x.d_hi)} pp"
                + (f" (Holm p {_p(x.p_holm)} *)" if _sig(x) else "")
            )
        sig = [x for x in boost.iloc[1:].itertuples() if _sig(x)]
        tail = (
            f" Smallest boost with a Holm-significant effect: {_f(sig[0].boost, 2)}."
            if sig
            else " No boost has a Holm-significant effect."
        )
        out.append(
            f"- Retrieval weighting (final scores span {_f(ss.get('median_top5_spread'), 3)} across the top 5 "
            f"at the median; the 5th-to-6th gap is {_f(ss.get('median_gap_5_6'), 3)}): "
            + "; ".join(parts)
            + "."
            + tail
        )
    if deltas is not None and "primary" in deltas.columns:
        out += claim_arms_v2(r)
    elif deltas is not None:
        d = deltas.set_index("arm")
        if "aa_resample" in d.index:
            a = d.loc["aa_resample"]
            out.append(
                f"- Noise floor: re-sampling the unchanged prompts (A/A) moved PAWC share by "
                f"{_ci(a.d_pwc_pp, a.d_pwc_lo, a.d_pwc_hi)} pp."
            )
        tested = deltas[~deltas.arm.isin(["noop", "aa_resample"])]
        sig = tested[tested.get("significant", False) == True]  # noqa: E712
        out.append(
            f"- Page and engine arms: {len(sig)} of {len(tested)} have a Holm-significant effect"
            + (": " + ", ".join(f"`{a}`" for a in sig.arm) if len(sig) else "")
            + "."
        )
    sens = sensitivity(r["dir"]) if deltas is None or "primary" not in deltas.columns else {}
    if sens:
        last = pos.iloc[-1] if pos is not None and len(pos) > 1 else None
        pos_sig = last is not None and bool(last.get("significant", False))
        boost_sig = boost is not None and any(_sig(x) for x in boost.iloc[1:].itertuples())
        page_rows = deltas[(deltas["kind"] == "doc") & ~deltas.arm.isin(["noop", "aa_resample"])]
        page_sig = bool(page_rows["significant"].any()) if len(page_rows) else False

        def lever(name: str, hit: bool, size) -> str:
            return f"{name}: {'**detected**' if hit else f'not detected (MDE ≈ {_f(size)} pp)'}"

        levers = [
            lever(
                f"Moving the target from slot 1 to slot {int(last.position)}"
                if last is not None
                else "Slot moves",
                pos_sig,
                sens.get("position_pp"),
            ),
            lever(
                f"small retrieval boosts (w ≤ {_f(boost.boost.max(), 2)})"
                if boost is not None
                else "boosts",
                boost_sig,
                sens.get("boost_pp"),
            ),
        ]
        k = sens.get("n_page_units")
        kmin = sens.get("n_page_units_min", k)
        units_txt = f"{kmin}–{k}" if kmin is not None and kmin != k else f"{k}"
        if k is not None and not sens.get("page_arms_testable"):
            levers.append(
                f"page edits: **untestable at this design** ({units_txt} independent page units per arm; the minimum "
                f"achievable Holm p is {_f(min(1.0, sens['min_exact_p_page_units'] * sens['arm_holm_family']), 3)}, "
                f"above 0.05 at any effect size)"
            )
        elif k is not None:
            levers.append(lever(f"page edits ({k} page units)", page_sig, sens.get("page_arm_pp")))
        out.append(
            f"- Sensitivity (80% power, strictest Holm step; A/A per-query SD "
            f"{_f(sens['aa_sd_per_query_pp'])} pp; slot sweep n={sens.get('position_n_queries')}, "
            f"boost sweep n={sens.get('boost_n_queries')} queries). "
            + "; ".join(levers)
            + ". Only the boosts and page edits are small changes; moving a source to the last slot "
            "is a large one. An effect the size of the MDE would be detected with 80% power; smaller ones "
            "could be missed. The sweep MDE uses the A/A per-query SD as its noise scale, so it is "
            "approximate for slot and boost comparisons, which have their own variance."
        )
    bandit = r.get("bandit")
    if bandit is not None and "eval" in bandit.columns:
        h = bandit[bandit["eval"] == "heldout"].set_index("policy")
        if {"linucb (frozen, contextual)", "random (expected)"} <= set(h.index):
            c, rnd = h.loc["linucb (frozen, contextual)"], h.loc["random (expected)"]
            fx = (
                h.loc["best fixed arm (chosen on train)"]
                if "best fixed arm (chosen on train)" in h.index
                else None
            )
            gen = c.final_regret + c.final_regret_ci < rnd.final_regret and (
                fx is None or c.final_regret <= fx.final_regret
            )
            out.append(
                f"- Bandit, held out: the frozen contextual policy had regret {_f(c.final_regret, 3)} "
                f"(±{_f(c.final_regret_ci, 3)}) vs {_f(rnd.final_regret, 3)} for random"
                + (
                    f" and {_f(fx.final_regret, 3)} for the best fixed arm chosen on the training half"
                    if fx is not None
                    else ""
                )
                + (
                    ". It beat random on the held-out queries by more than its 95% interval."
                    if gen
                    else ". On the held-out queries it is not distinguishable from random."
                )
            )
    return "\n".join(out)


def page_means(d: Path, metric: str, arms: list[str]) -> dict[str, float]:
    """Arm minus baseline in pp, averaged within each edited page and then across pages (the
    scale the page-unit Wilcoxon test works on)."""
    pq_p, q_p = d / "per_query.csv", d / "queries.csv"
    if not arms or not pq_p.exists() or not q_p.exists():
        return {}
    pq = pd.read_csv(pq_p)
    q = pd.read_csv(q_p).set_index("query_id")
    if metric not in pq or "focus_doc" not in q:
        return {}
    base = pq[pq.arm == "baseline"].set_index("query_id")[metric]
    out = {}
    for a in arms:
        x = pq[pq.arm == a].set_index("query_id")[metric]
        if len(x):
            delta = (x - base.reindex(x.index)).dropna() * 100
            out[a] = float(delta.groupby(q.loc[delta.index, "focus_doc"]).mean().mean())
    return out


def claim_arms_v2(r: dict) -> list[str]:
    """Verdict lines for runs with a primary metric: noise floor, arms per Holm family, mentions,
    the content/rank split and what the design could detect."""
    deltas, pos = r["deltas"], r["position"]
    primary = deltas["primary"].iloc[0]
    col = {"c_share": "csov", "imp_pwc": "pwc", "mentioned": "mention"}[primary]
    name = {"c_share": "C-SoV", "imp_pwc": "PAWC share", "mentioned": "named rate"}[primary]
    out = []
    d = deltas.set_index("arm")
    sp = r.get("sampled_primary") if primary == "c_share" else None
    sp_aa = next((c for c in sp["controls"] if c["arm"] == "aa_resample"), None) if sp else None
    if sp_aa and "aa_resample" in d.index:
        a = d.loc["aa_resample"]
        out.append(
            f"- Noise floor: re-sampling the unchanged prompts (A/A) moved {name} by "
            f"{_ci(sp_aa['d_c_share_pp'], sp_aa['lo'], sp_aa['hi'])} pp on "
            f"{sp_aa['n_pages']} page units (raw sign-flip p {_p(sp_aa['p_perm'])}) and the "
            f"named rate by {_ci(a.d_mention_pp, a.d_mention_lo, a.d_mention_hi)} pp."
        )
    elif "aa_resample" in d.index:
        a = d.loc["aa_resample"]
        out.append(
            f"- Noise floor: re-sampling the unchanged prompts (A/A) moved {name} by "
            f"{_ci(a[f'd_{col}_pp'], a[f'd_{col}_lo'], a[f'd_{col}_hi'])} pp and the named rate by "
            f"{_ci(a.d_mention_pp, a.d_mention_lo, a.d_mention_hi)} pp."
        )
    tested = deltas[~deltas.arm.isin(["noop", "aa_resample"])]
    for fam, label_ in (("arms", "Page and engine arms"), ("content", "Content-only arms")):
        g = tested[tested["family"] == fam]
        if not len(g):
            continue
        sig = g[g["significant"] == True]  # noqa: E712
        rule = "a Holm-significant effect"
        if sp and fam == "arms":
            hit = {x["arm"] for x in sp["arms"] if x["significant"]}
            sig = g[g.arm.isin(hit)]
            rule = "an effect under the sampled primary rule"
        msig = g[g["mention_significant"] == True]  # noqa: E712
        out.append(
            f"- {label_}: {len(sig)} of {len(g)} have {rule} on {name}"
            + (": " + ", ".join(f"`{a}`" for a in sig.arm) if len(sig) else "")
            + f"; {len(msig)} of {len(g)} on the named rate"
            + (": " + ", ".join(f"`{a}`" for a in msig.arm) if len(msig) else "")
            + "."
        )
    if sp and sp.get("exploratory_reference"):
        parts = []
        for ref, rs in sp["exploratory_reference"].items():
            parts.append(
                f"against the {ref} "
                + ", ".join(
                    f"`{x['arm']}` {_f(x['d_c_share_pp'], sign=True)} (Holm p "
                    f"{_p(x['p_wilcoxon_holm'])} / {_p(x['p_perm_exact_holm'])})"
                    for x in rs
                )
            )
        out.append(
            "- Exploratory, not pre-registered (the reference choice, `sampled_primary.md`): "
            + "; ".join(parts)
            + ". A lucky baseline draw shifts every arm the same way; an arm that holds up only "
            "against the baseline alone is not robust to that choice."
        )
    dec = r.get("decomposition")
    if dec is not None and len(dec):
        big = dec.loc[(dec[f"rank_{col}_pp"].abs() > dec[f"content_{col}_pp"].abs())]
        out.append(
            f"- Content vs rank: for {len(big)} of {len(dec)} page edits the rank-mediated part of the "
            f"{name} change is larger in size than the content-only part (point estimates; see the "
            "decomposition table for intervals)."
        )
    pm = page_means(r["dir"], primary, list(tested[tested["kind"] == "doc"].arm))
    if r["manifest"].get("weighting") == "page":
        out.append(
            f"- Weighting: the {name} estimates, intervals and tests above all use unweighted "
            "page means."
        )
    elif pm:
        out.append(
            f"- Weighting: the {name} estimates and intervals above weight every query equally, "
            "while the Wilcoxon test ranks unweighted page means. The page means are "
            + ", ".join(f"`{a}` {_f(v)}" for a, v in pm.items())
            + " pp."
        )
    sens = sensitivity(r["dir"])
    if sens and not sens.get("arm_holm_family"):
        out.append(
            "- No page arms in this run (a pilot), so it states no MDE of its own; "
            "`vizor sensitivity <dir> --family N` gives the MDE for a planned design."
        )
        sens = {}
    planned = bool(sens.get("families_from_plan")) and "planned_arms" in r["manifest"]
    if sens:
        parts = []
        if sens.get("page_arm_page_pp") is not None:
            t_pp = sens.get("page_arm_page_t_pp")
            parts.append(
                f"page edits ≈ {_f(sens['page_arm_page_pp'])} pp"
                + (f" ({_f(t_pp)} pp with t quantiles)" if t_pp is not None else "")
                + f" on {sens['n_units_page']} underlying page units (both cross-fit folds "
                "clustered by page)"
            )
        elif sens.get("n_page_units") is not None:
            parts.append("page edits: **untestable at this design** (too few page units)")
        if sens.get("content_arm_page_pp") is not None:
            parts.append(f"content-only arms ≈ {_f(sens['content_arm_page_pp'])} pp")
        if sens.get("mention_page_arm_pp") is not None:
            parts.append(f"named rate for page edits ≈ {_f(sens['mention_page_arm_pp'])} pp")
        if sens.get("position_pp") is not None:
            parts.append(f"slot sweep ≈ {_f(sens['position_pp'])} pp")
        design = (
            f"for the planned design of {sens['arm_holm_family']} page edits and "
            f"{sens['content_holm_family']} content-only twins, each its own Holm family; "
            if planned
            else ""
        )
        out.append(
            f"- Minimum detectable effect on {name} ({design}80% power, strictest Holm step, "
            "normal approximation, from the A/A "
            f"re-sample; per-query A/A SD {_f(sens['aa_sd_per_query_pp'])} pp): "
            + "; ".join(parts)
            + ". These are approximate: the test is a Wilcoxon signed-rank test, not a t test. "
            "Effects smaller than these could be missed."
        )
    if pos is not None and len(pos) > 1 and "primary" in pos.columns:
        x = pos.iloc[-1]
        out.append(
            f"- Positive control (target moved from slot {int(pos.position.iloc[0])} to slot "
            f"{int(x.position)}, same pages): {name} "
            + _ci(
                x[f"d_{'csov' if col == 'csov' else 'pwc'}_vs_first_pp"],
                x["d_csov_lo" if col == "csov" else "d_lo"],
                x["d_csov_hi" if col == "csov" else "d_hi"],
            )
            + f" pp, Holm p {_p(x.get('p_holm'))}"
            + (" *" if _sig(x) else "")
            + "."
        )
    return out


def bandit_md(r: dict) -> str:
    full = r["bandit"]
    if "eval" not in full.columns:
        full = full.assign(eval="replay")
    df = full[full["eval"] == "replay"]
    held = full[full["eval"] == "heldout"]
    m = r["manifest"]["config"]["bandit"]
    reward = {"imp_pwc": "PAWC share", "c_share": "citation share", "mentioned": "named rate"}[
        r["manifest"].get("primary_metric", "imp_pwc")
    ]

    def arm_cell(x) -> str:
        return (
            f"`{x.top_arm}` ({_f(x.top_arm_share * 100, 0)}%)"
            if isinstance(x.top_arm, str) and x.top_arm
            else ""
        )

    rows = [
        [
            x.policy,
            f"{_f(x.final_regret, 2)} ± {_f(x.final_regret_ci, 2)}",
            _f(x.mean_reward_pp, 2, True),
            arm_cell(x),
        ]
        for x in df.itertuples()
    ]
    out = (
        f"Offline replay uses rewards from the same table the policies learn from. It runs "
        f"{m['rounds']} rounds x {m['runs']} runs. Regret is summed over rounds in {reward} "
        f"(1.0 = 100 pp). The hindsight row knows the best single arm in advance and serves as "
        f"a reference, not a policy.\n\n"
        + _table(
            [
                "Policy",
                "Cumulative regret at T (±95% CI)",
                "Mean reward pp/round",
                "Most chosen arm",
            ],
            rows,
        )
    )
    if len(held):
        out += (
            "\n\nHeld-out check: the policy is fit on fold-1 queries, then frozen and scored on "
            "fold-2 queries. Regret is summed over held-out queries, with one decision per query. "
            "Caveat: for the cross-fitted arms (metadata, FAQ, keyword stuffing) the fold-1 rewards were "
            "measured on pages built from fold-2 query text, so this is a split of contexts rather than "
            "a fully independent test.\n\n"
            + _table(
                ["Policy", "Held-out regret (±95% CI)", "Mean reward pp", "Most chosen arm"],
                [
                    [
                        x.policy,
                        f"{_f(x.final_regret, 3)} ± {_f(x.final_regret_ci, 3)}",
                        _f(x.mean_reward_pp, 2, True),
                        arm_cell(x),
                    ]
                    for x in held.itertuples()
                ],
            )
        )
    return out


def trajectory_md(r: dict) -> str:
    df = r["trajectory"]
    rows = [
        [
            str(int(x.step)),
            f"`{x.proposed}`",
            _f(x.predicted_reward_pp, 2, True),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi, 2),
            "kept" if x.kept else "rejected",
            f"`{x.applied}`",
            _f(x.heldout_pwc_pct),
        ]
        for x in df.itertuples()
    ]
    return (
        f"Held-out queries: {int(df.n_heldout.iloc[0])}. The loop keeps an arm only when the lower "
        f"95% confidence bound on held-out ΔPAWC is above zero.\n\n"
        + _table(
            [
                "Step",
                "Proposed",
                "Predicted pp",
                "Held-out ΔPAWC pp [95% CI]",
                "Decision",
                "Applied so far",
                "Held-out PAWC %",
            ],
            rows,
        )
    )


def summary_md(r: dict, level: int = 1) -> str:
    h = "#" * level
    parts = [f"{h} {label(r)}", header_md(r)]
    if r.get("invalid_reason"):
        return "\n\n".join([*parts, f"**Invalid result:** {r['invalid_reason']}"]) + "\n"
    if r["domains"] is not None:
        parts += [
            f"{h}# Baseline visibility",
            "Pooled marker share is the domain's share of all valid markers across every answer, "
            "so long, heavily cited answers count for more. It is not the per-answer C-SoV used "
            "as the primary metric in the arm tables, which averages each answer's own share.",
            domains_md(r),
        ]
    if r["deltas"] is not None:
        parts += [f"{h}# Sandbox arms (target: {_target(r)})", deltas_md(r)]
    if decomposition_md(r):
        parts += [f"{h}# Content vs rank", decomposition_md(r)]
    if r["position"] is not None:
        parts += [f"{h}# Position sweep", position_md(r)]
    if r["boost"] is not None:
        parts += [f"{h}# Boost sweep", boost_md(r)]
    claim = claim_md(r)
    if claim:
        parts += [f"{h}# What the sweeps show", claim]
    if r["bandit"] is not None:
        parts += [f"{h}# Bandit replay", bandit_md(r)]
    if r["trajectory"] is not None:
        parts += [f"{h}# Greedy optimization loop", trajectory_md(r)]
    return "\n\n".join(parts) + "\n"


def _target(r: dict) -> str:
    df = r["domains"]
    t = df[df.role == "target"].domain.tolist() if df is not None else []
    return ", ".join(t) or "target"


def write_summary(d: Path) -> Path:
    p = d / "summary.md"
    p.write_text(summary_md(load(d)))
    return p


def _order(results: list[dict]) -> list[dict]:
    return sorted(results, key=lambda r: (r["manifest"].get("llm_is_fake", False), str(r["dir"])))


def refresh_sensitivity(d: Path) -> bool:
    """Recompute the manifest's `sensitivity` block from the result files (no LLM calls).
    Returns True when it changed. Nothing else in the manifest is touched."""
    p = d / "manifest.json"
    m = json.loads(p.read_text())
    if "primary_metric" not in m:  # runs from before the bench code are left as they were
        return False
    new = json.loads(json.dumps(sensitivity(d, metric=m.get("primary_metric")), default=str))
    if m.get("sensitivity") == new:
        return False
    m["sensitivity"] = new
    p.write_text(json.dumps(m, indent=2, default=str) + "\n")
    return True


def write_results(dirs: list[Path], out: Path, readme: Path | None = None) -> None:
    for d in dirs:
        if (d / "manifest.json").exists() and (d / "per_query.csv").exists():
            refresh_sensitivity(d)
    results = _order([load(d) for d in dirs if (d / "manifest.json").exists()])
    for r in results:
        write_summary(r["dir"])
    body = [
        "# Results",
        "`vizor report` builds this page from the run directories under `experiments/results/`. "
        "All numbers come from those files. See `experiments/README.md` for reproduction steps.",
    ]
    body += [summary_md(r, level=2) for r in results]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n\n".join(body).rstrip() + "\n")
    if readme is not None and results:
        text = readme.read_text()
        if README_START in text and README_END in text:
            block = readme_block(results)
            text = re.sub(
                re.escape(README_START) + ".*?" + re.escape(README_END),
                lambda _: f"{README_START}\n{block}\n{README_END}",
                text,
                flags=re.S,
            )
            readme.write_text(text)


def readme_block(results: list[dict]) -> str:
    parts = []
    for r in results:
        parts.append(f"#### {label(r)}")
        parts.append(header_md(r))
        if r.get("invalid_reason"):
            parts.append(f"**Invalid result:** {r['invalid_reason']}")
            continue
        if r["deltas"] is not None:
            keep = r["deltas"]
            parts.append(deltas_md({**r, "deltas": keep}))
        if decomposition_md(r):
            parts.append(decomposition_md(r))
        if r["position"] is not None:
            parts.append(position_md(r))
        if r["boost"] is not None:
            parts.append(boost_md(r))
        claim = claim_md(r)
        if claim:
            parts.append(claim)
    return "\n\n".join(parts)
