"""Markdown reports generated from results directories. Nothing in them is typed by hand."""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

import pandas as pd

from vizor.optimize.sensitivity import sensitivity

README_START = "<!-- results:start (generated by `vizor report`, do not edit) -->"
README_END = "<!-- results:end -->"


def _f(x, digits: int = 1, sign: bool = False) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:+.{digits}f}" if sign else f"{x:.{digits}f}"


def _ci(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits, True)} [{_f(lo, digits, True)}, {_f(hi, digits, True)}]"


def _lvl(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits)} [{_f(lo, digits)}, {_f(hi, digits)}]"


def _p(p) -> str:
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    return "<0.001" if p < 0.001 else f"{p:.3f}"


def _table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _read(d: Path, name: str) -> pd.DataFrame | None:
    p = d / name
    return pd.read_csv(p) if p.exists() else None


def load(d: Path) -> dict:
    return {
        "dir": d,
        "manifest": json.loads((d / "manifest.json").read_text()),
        "domains": _read(d, "baseline_domains.csv"),
        "deltas": _read(d, "deltas.csv"),
        "position": _read(d, "position_sweep.csv"),
        "boost": _read(d, "boost_sweep.csv"),
        "bandit": _read(d, "bandit_summary.csv"),
        "trajectory": _read(d, "trajectory.csv"),
    }


def label(r: dict) -> str:
    m = r["manifest"]
    if m.get("llm_is_fake"):
        return "FakeLLM (pipeline check)"
    if m["config"]["llm"]["backend"] == "ollama":
        return f"{m['llm_model']} via Ollama (small local model, reduced design)"
    return m["llm_model"]


def header_md(r: dict) -> str:
    m = r["manifest"]
    usage = m.get("llm_usage") or {}
    lines = [
        f"- Results: `{r['dir'].as_posix()}` (git {m.get('git_commit')}, {m.get('started', '')[:10]})",
        f"- Answer model: `{m['llm_model']}`"
        + (
            " (deterministic extractive stand-in; pipeline check, not model evidence)"
            if m.get("llm_is_fake")
            else ""
        ),
        f"- Retrieval: `{m['embedder_id']}` + `{m['reranker_id']}`, index `{m.get('index_backend')}`",
        f"- Sentiment: `{m['sentiment_backend']}`; PAWC decay: {m['decay']}",
        f"- {m['n_queries']} queries x {m['samples']} samples, {m['n_docs']} pages",
    ]
    if m["config"]["llm"]["backend"] == "ollama":
        lines.append(
            "- This is a small local model. It needed an extra system message (recorded in the "
            "manifest) to cite in-line."
        )
    if usage and m["config"]["llm"]["backend"] == "ollama":
        lines.append(
            f"- Local calls: {usage.get('calls', 0)} new, {usage.get('cache_hits', 0)} cached (no API spend)"
        )
    elif usage:
        lines.append(
            f"- API calls: {usage.get('calls', 0)} new, {usage.get('cache_hits', 0)} cached; "
            f"estimated spend ${usage.get('spent_usd', 0):.2f} (list prices)"
        )
    if m.get("skipped_due_to_budget"):
        lines.append(f"- Skipped (budget cap reached): {', '.join(m['skipped_due_to_budget'])}")
    return "\n".join(lines)


def domains_md(r: dict) -> str:
    df = r["domains"]
    rows = [
        [
            f"{x.domain}{' (target)' if x.role == 'target' else ''}",
            _f(x.retrieval_rate * 100, 0),
            _f(x.citation_rate * 100, 0),
            _f(x.conversion * 100, 0),
            _f(x.c_sov * 100),
            _f(x.pawc_sov * 100),
            _f(x.first_cite_sentence, 2),
            _f(x.ignored_rate * 100, 0),
            _f(x.answer_sentiment, 2, True),
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Domain",
            "Retrieved %",
            "Cited %",
            "Cited when retrieved %",
            "C-SoV %",
            "PAWC share %",
            "First cite (sentence)",
            "Ignored when retrieved %",
            "Answer sentiment",
        ],
        rows,
    )


def deltas_md(r: dict) -> str:
    df = r["deltas"]
    ctrl = ("noop", "aa_resample")
    rows = [
        [
            f"`{x.arm}`",
            _ci(x.d_pwc_pp, x.d_pwc_lo, x.d_pwc_hi),
            _f(x.rel_pct, 0, True) if not pd.isna(x.rel_pct) else "n/a",
            _ci(x.d_csov_pp, x.d_csov_lo, x.d_csov_hi),
            _f(x.d_cite_rate_pp, 1, True),
            _f(getattr(x, "d_pwc_given_cited_pp", float("nan")), 1, True),
            _f(getattr(x, "uncited_rate_pct", float("nan")), 0),
            _f(x.d_sentiment, 3, True),
            _p(x.p_holm) + (" *" if getattr(x, "significant", False) else "")
            if x.arm not in ctrl
            else "control",
            f"{int(x.n_queries)} / {int(getattr(x, 'n_units', x.n_queries))}",
        ]
        for x in df.itertuples()
    ]
    note = (
        "An arm counts as having an effect when its Holm-adjusted Wilcoxon p-value is below "
        "0.05 (`*`). The 95% confidence intervals are descriptive. `noop` and `aa_resample` are "
        "controls and are excluded from the Holm family. Page arms change each query's focus page. "
        "They are tested across (fold, page) units because queries that share an edited page are "
        "not independent; `n` reports queries / units. Arms that use the tracked queries are "
        "cross-fitted: built on one half of the queries and scored on the other. "
        '"ΔPAWC if cited" counts only answers with citations. Citation-format failures instead '
        "appear in the uncited rate."
    )
    return (
        note
        + "\n\n"
        + _table(
            [
                "Arm",
                "ΔPAWC pp [95% CI]",
                "Rel Δ %",
                "ΔC-SoV pp [95% CI]",
                "Δ cited pp",
                "ΔPAWC if cited pp",
                "Uncited answers %",
                "Δ sentiment",
                "p (Holm)",
                "n",
            ],
            rows,
        )
    )


def position_md(r: dict) -> str:
    df = r["position"]
    rows = [
        [
            str(int(x.position)),
            _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
            _ci(x.d_pwc_vs_first_pp, x.d_lo, x.d_hi)
            if x.position != df.position.iloc[0]
            else "ref",
            _f(x.cite_rate_pct, 0),
            (_p(x.p_holm) + (" *" if _sig(x) else ""))
            if x.position != df.position.iloc[0] and hasattr(x, "p_holm")
            else "",
            str(int(x.n_queries)),
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Target slot",
            "PAWC share % [95% CI]",
            "Δ vs slot 1 pp [95% CI]",
            "Cited %",
            "p (Holm, sweeps)",
            "n",
        ],
        rows,
    )


def boost_md(r: dict) -> str:
    df = r["boost"]
    rows = [
        [
            _f(x.boost, 2),
            _f(x.retrieval_pct, 0),
            _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi) if x.boost != 0 else "ref",
            _f(x.cite_rate_pct, 0),
            (_p(x.p_holm) + (" *" if _sig(x) else ""))
            if x.boost != 0 and hasattr(x, "p_holm")
            else "",
            _cls(x, "set_changed") if x.boost != 0 else "",
            _cls(x, "order_only") if x.boost != 0 else "",
            _cls(x, "unchanged") if x.boost != 0 else "",
        ]
        for x in df.itertuples()
    ]
    return (
        "For each query, these classes compare the boosted source list with w=0: a different set "
        "of sources, the same sources in a different order, or no change. Each cell shows "
        "`n queries: mean ΔPAWC pp`.\n\n"
        + _table(
            [
                "Boost w",
                "Target retrieved %",
                "PAWC share % [95% CI]",
                "Δ vs w=0 pp [95% CI]",
                "Cited %",
                "p (Holm, sweeps)",
                "Set changed",
                "Order only",
                "Unchanged",
            ],
            rows,
        )
    )


def _cls(x, c: str) -> str:
    n = getattr(x, f"n_{c}", None)
    if n is None or (isinstance(n, float) and math.isnan(n)):
        return ""
    d = getattr(x, f"d_pwc_{c}_pp")
    return f"{int(n)}: {_f(d, 1, True)}" if n else "0"


def _sig(x) -> bool:
    return bool(getattr(x, "significant", False)) and not pd.isna(
        getattr(x, "p_holm", float("nan"))
    )


def claim_md(r: dict) -> str:
    """What the sweeps and arms measured, stated only through the Holm verdict rule and the MDE."""
    m, pos, boost, deltas = r["manifest"], r["position"], r["boost"], r["deltas"]
    if m.get("llm_is_fake"):
        return (
            f"- FakeLLM applies an explicit −{m.get('fake_llm_position_prior') or 0.05:g} per-slot position "
            "penalty; this sweep recovers that built-in prior and is not evidence about real models."
        )
    out = []
    if pos is not None and len(pos) > 1:
        slots = ", ".join(f"slot {int(x.position)} {_f(x.pwc_pct)}%" for x in pos.itertuples())
        sig = [x for x in pos.iloc[1:].itertuples() if _sig(x)]
        if sig:
            detail = "; ".join(
                f"slot {int(x.position)} vs 1: {_ci(x.d_pwc_vs_first_pp, x.d_lo, x.d_hi)} pp (Holm p {_p(x.p_holm)})"
                for x in sig
            )
            verdict = f"Holm-significant differences: {detail}."
        else:
            verdict = "No slot differs from slot 1 under the Holm rule."
        out.append(
            f"- Context order (same pages, target forced into each slot, n={int(pos.n_queries.iloc[0])} queries): "
            f"PAWC share {slots}. {verdict}"
        )
    if boost is not None and len(boost) > 1:
        ss = m.get("score_scale", {})
        parts = []
        base_ret = boost.iloc[0].retrieval_pct
        for x in boost.iloc[1:].itertuples():
            ret = (
                f"target retrieval unchanged at {_f(x.retrieval_pct, 0)}%"
                if abs(x.retrieval_pct - base_ret) < 1e-9
                else f"target retrieval {_f(base_ret, 0)}% → {_f(x.retrieval_pct, 0)}%"
            )
            parts.append(
                f"w={_f(x.boost, 2)}: {ret}, ΔPAWC {_ci(x.d_pwc_pp, x.d_lo, x.d_hi)} pp"
                + (f" (Holm p {_p(x.p_holm)} *)" if _sig(x) else "")
            )
        sig = [x for x in boost.iloc[1:].itertuples() if _sig(x)]
        tail = (
            f" Smallest boost with a Holm-significant effect: {_f(sig[0].boost, 2)}."
            if sig
            else " No boost has a Holm-significant effect."
        )
        out.append(
            f"- Retrieval weighting (final scores span {_f(ss.get('median_top5_spread'), 3)} across the top 5 "
            f"at the median; the 5th-to-6th gap is {_f(ss.get('median_gap_5_6'), 3)}): "
            + "; ".join(parts)
            + "."
            + tail
        )
    if deltas is not None:
        d = deltas.set_index("arm")
        if "aa_resample" in d.index:
            a = d.loc["aa_resample"]
            out.append(
                f"- Noise floor: re-sampling the unchanged prompts (A/A) moved PAWC share by "
                f"{_ci(a.d_pwc_pp, a.d_pwc_lo, a.d_pwc_hi)} pp."
            )
        tested = deltas[~deltas.arm.isin(["noop", "aa_resample"])]
        sig = tested[tested.get("significant", False) == True]  # noqa: E712
        out.append(
            f"- Page and engine arms: {len(sig)} of {len(tested)} have a Holm-significant effect"
            + (": " + ", ".join(f"`{a}`" for a in sig.arm) if len(sig) else "")
            + "."
        )
    sens = sensitivity(r["dir"])
    if sens:
        last = pos.iloc[-1] if pos is not None and len(pos) > 1 else None
        pos_sig = last is not None and bool(last.get("significant", False))
        boost_sig = boost is not None and any(_sig(x) for x in boost.iloc[1:].itertuples())
        page_rows = deltas[(deltas["kind"] == "doc") & ~deltas.arm.isin(["noop", "aa_resample"])]
        page_sig = bool(page_rows["significant"].any()) if len(page_rows) else False

        def lever(name: str, hit: bool, size) -> str:
            return f"{name}: {'**detected**' if hit else f'not detected (MDE ≈ {_f(size)} pp)'}"

        levers = [
            lever(
                f"Moving the target from slot 1 to slot {int(last.position)}"
                if last is not None
                else "Slot moves",
                pos_sig,
                sens.get("position_pp"),
            ),
            lever(
                f"small retrieval boosts (w ≤ {_f(boost.boost.max(), 2)})"
                if boost is not None
                else "boosts",
                boost_sig,
                sens.get("boost_pp"),
            ),
        ]
        k = sens.get("n_page_units")
        if k is not None and not sens.get("page_arms_testable"):
            levers.append(
                f"page edits: **not testable** with {k} independent page units (the smallest exact "
                f"Wilcoxon p is {_f(sens['min_exact_p_page_units'], 4)}, above 0.05 after Holm across "
                f"{sens['arm_holm_family']} arms, at any effect size)"
            )
        elif k is not None:
            levers.append(lever(f"page edits ({k} page units)", page_sig, sens.get("page_arm_pp")))
        out.append(
            f"- Sensitivity (80% power, strictest Holm step; A/A per-query SD "
            f"{_f(sens['aa_sd_per_query_pp'])} pp; slot sweep n={sens.get('position_n_queries')}, "
            f"boost sweep n={sens.get('boost_n_queries')} queries). "
            + "; ".join(levers)
            + ". Only the boosts and page edits are small changes; moving a source to the last slot "
            "is a large one. A non-detection rules out effects above the MDE, not smaller ones."
        )
    bandit = r.get("bandit")
    if bandit is not None and "eval" in bandit.columns:
        h = bandit[bandit["eval"] == "heldout"].set_index("policy")
        if {"linucb (frozen, contextual)", "random (expected)"} <= set(h.index):
            c, rnd = h.loc["linucb (frozen, contextual)"], h.loc["random (expected)"]
            fx = (
                h.loc["best fixed arm (chosen on train)"]
                if "best fixed arm (chosen on train)" in h.index
                else None
            )
            gen = c.final_regret + c.final_regret_ci < rnd.final_regret and (
                fx is None or c.final_regret <= fx.final_regret
            )
            out.append(
                f"- Bandit, held out: the frozen contextual policy had regret {_f(c.final_regret, 3)} "
                f"(±{_f(c.final_regret_ci, 3)}) vs {_f(rnd.final_regret, 3)} for random"
                + (
                    f" and {_f(fx.final_regret, 3)} for the best fixed arm chosen on the training half"
                    if fx is not None
                    else ""
                )
                + (
                    ". It beat random on the held-out queries by more than its 95% interval."
                    if gen
                    else ". On the held-out queries it is not distinguishable from random."
                )
            )
    return "\n".join(out)


def bandit_md(r: dict) -> str:
    full = r["bandit"]
    if "eval" not in full.columns:
        full = full.assign(eval="replay")
    df = full[full["eval"] == "replay"]
    held = full[full["eval"] == "heldout"]
    m = r["manifest"]["config"]["bandit"]

    def arm_cell(x) -> str:
        return (
            f"`{x.top_arm}` ({_f(x.top_arm_share * 100, 0)}%)"
            if isinstance(x.top_arm, str) and x.top_arm
            else ""
        )

    rows = [
        [
            x.policy,
            f"{_f(x.final_regret, 2)} ± {_f(x.final_regret_ci, 2)}",
            _f(x.mean_reward_pp, 2, True),
            arm_cell(x),
        ]
        for x in df.itertuples()
    ]
    out = (
        f"Offline replay uses rewards from the same table the policies learn from. It runs "
        f"{m['rounds']} rounds x {m['runs']} runs. Regret is summed over rounds in PAWC share "
        f"(1.0 = 100 pp). The hindsight row knows the best single arm in advance and serves as "
        f"a reference, not a policy.\n\n"
        + _table(
            [
                "Policy",
                "Cumulative regret at T (±95% CI)",
                "Mean reward pp/round",
                "Most chosen arm",
            ],
            rows,
        )
    )
    if len(held):
        out += (
            "\n\nHeld-out check: the policy is fit on fold-1 queries, then frozen and scored on "
            "fold-2 queries. Regret is summed over held-out queries, with one decision per query. "
            "Caveat: for the cross-fitted arms (metadata, FAQ, keyword stuffing) the fold-1 rewards were "
            "measured on pages built from fold-2 query text, so this is a split of contexts rather than "
            "a fully independent test.\n\n"
            + _table(
                ["Policy", "Held-out regret (±95% CI)", "Mean reward pp", "Most chosen arm"],
                [
                    [
                        x.policy,
                        f"{_f(x.final_regret, 3)} ± {_f(x.final_regret_ci, 3)}",
                        _f(x.mean_reward_pp, 2, True),
                        arm_cell(x),
                    ]
                    for x in held.itertuples()
                ],
            )
        )
    return out


def trajectory_md(r: dict) -> str:
    df = r["trajectory"]
    rows = [
        [
            str(int(x.step)),
            f"`{x.proposed}`",
            _f(x.predicted_reward_pp, 2, True),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi),
            "kept" if x.kept else "rejected",
            f"`{x.applied}`",
            _f(x.heldout_pwc_pct),
        ]
        for x in df.itertuples()
    ]
    return (
        f"Held-out queries: {int(df.n_heldout.iloc[0])}. The loop keeps an arm only when the lower "
        f"95% confidence bound on held-out ΔPAWC is above zero.\n\n"
        + _table(
            [
                "Step",
                "Proposed",
                "Predicted pp",
                "Held-out ΔPAWC pp [95% CI]",
                "Decision",
                "Applied so far",
                "Held-out PAWC %",
            ],
            rows,
        )
    )


def summary_md(r: dict, level: int = 1) -> str:
    h = "#" * level
    parts = [f"{h} {label(r)}", header_md(r)]
    if r["domains"] is not None:
        parts += [f"{h}# Baseline visibility", domains_md(r)]
    if r["deltas"] is not None:
        parts += [f"{h}# Sandbox arms (target: {_target(r)})", deltas_md(r)]
    if r["position"] is not None:
        parts += [f"{h}# Position sweep", position_md(r)]
    if r["boost"] is not None:
        parts += [f"{h}# Boost sweep", boost_md(r)]
    claim = claim_md(r)
    if claim:
        parts += [f"{h}# What the sweeps show", claim]
    if r["bandit"] is not None:
        parts += [f"{h}# Bandit replay", bandit_md(r)]
    if r["trajectory"] is not None:
        parts += [f"{h}# Greedy optimization loop", trajectory_md(r)]
    return "\n\n".join(parts) + "\n"


def _target(r: dict) -> str:
    df = r["domains"]
    t = df[df.role == "target"].domain.tolist() if df is not None else []
    return ", ".join(t) or "target"


def write_summary(d: Path) -> Path:
    p = d / "summary.md"
    p.write_text(summary_md(load(d)))
    return p


def _order(results: list[dict]) -> list[dict]:
    return sorted(results, key=lambda r: (r["manifest"].get("llm_is_fake", False), str(r["dir"])))


def write_results(dirs: list[Path], out: Path, readme: Path | None = None) -> None:
    results = _order([load(d) for d in dirs if (d / "manifest.json").exists()])
    for r in results:
        write_summary(r["dir"])
    body = [
        "# Results",
        "`vizor report` builds this page from the run directories under `experiments/results/`. "
        "All numbers come from those files. See `experiments/README.md` for reproduction steps.",
    ]
    body += [summary_md(r, level=2) for r in results]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n\n".join(body).rstrip() + "\n")
    if readme is not None and results:
        text = readme.read_text()
        if README_START in text and README_END in text:
            block = readme_block(results)
            text = re.sub(
                re.escape(README_START) + ".*?" + re.escape(README_END),
                lambda _: f"{README_START}\n{block}\n{README_END}",
                text,
                flags=re.S,
            )
            readme.write_text(text)


def readme_block(results: list[dict]) -> str:
    parts = []
    for r in results:
        parts.append(f"#### {label(r)}")
        parts.append(header_md(r))
        if r["deltas"] is not None:
            keep = r["deltas"]
            parts.append(deltas_md({**r, "deltas": keep}))
        if r["position"] is not None:
            parts.append(position_md(r))
        if r["boost"] is not None:
            parts.append(boost_md(r))
        claim = claim_md(r)
        if claim:
            parts.append(claim)
    return "\n\n".join(parts)
