"""Markdown reports generated from results directories. Nothing in them is typed by hand."""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

import pandas as pd

README_START = "<!-- results:start (generated by `vizor report`, do not edit) -->"
README_END = "<!-- results:end -->"


def _f(x, digits: int = 1, sign: bool = False) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:+.{digits}f}" if sign else f"{x:.{digits}f}"


def _ci(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits, True)} [{_f(lo, digits, True)}, {_f(hi, digits, True)}]"


def _lvl(m, lo, hi, digits: int = 1) -> str:
    return f"{_f(m, digits)} [{_f(lo, digits)}, {_f(hi, digits)}]"


def _p(p) -> str:
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    return "<0.001" if p < 0.001 else f"{p:.3f}"


def _table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _read(d: Path, name: str) -> pd.DataFrame | None:
    p = d / name
    return pd.read_csv(p) if p.exists() else None


def load(d: Path) -> dict:
    return {
        "dir": d,
        "manifest": json.loads((d / "manifest.json").read_text()),
        "domains": _read(d, "baseline_domains.csv"),
        "deltas": _read(d, "deltas.csv"),
        "position": _read(d, "position_sweep.csv"),
        "boost": _read(d, "boost_sweep.csv"),
        "bandit": _read(d, "bandit_summary.csv"),
        "trajectory": _read(d, "trajectory.csv"),
    }


def label(r: dict) -> str:
    m = r["manifest"]
    return "FakeLLM (pipeline check)" if m.get("llm_is_fake") else m["llm_model"]


def header_md(r: dict) -> str:
    m = r["manifest"]
    usage = m.get("llm_usage") or {}
    lines = [
        f"- Results: `{r['dir'].as_posix()}` (git {m.get('git_commit')}, {m.get('started', '')[:10]})",
        f"- Answer model: `{m['llm_model']}`"
        + (
            " (deterministic extractive stand-in: a pipeline check, not model evidence)"
            if m.get("llm_is_fake")
            else ""
        ),
        f"- Retrieval: `{m['embedder_id']}` + `{m['reranker_id']}`, index `{m.get('index_backend')}`",
        f"- Sentiment: `{m['sentiment_backend']}`; PAWC decay: {m['decay']}",
        f"- {m['n_queries']} queries x {m['samples']} samples, {m['n_docs']} pages",
    ]
    if usage:
        lines.append(
            f"- API calls: {usage.get('calls', 0)} new, {usage.get('cache_hits', 0)} cached; "
            f"estimated spend ${usage.get('spent_usd', 0):.2f} (list prices)"
        )
    if m.get("skipped_due_to_budget"):
        lines.append(f"- Skipped (budget cap reached): {', '.join(m['skipped_due_to_budget'])}")
    return "\n".join(lines)


def domains_md(r: dict) -> str:
    df = r["domains"]
    rows = [
        [
            f"{x.domain}{' (target)' if x.role == 'target' else ''}",
            _f(x.retrieval_rate * 100, 0),
            _f(x.citation_rate * 100, 0),
            _f(x.conversion * 100, 0),
            _f(x.c_sov * 100),
            _f(x.pawc_sov * 100),
            _f(x.first_cite_sentence, 2),
            _f(x.ignored_rate * 100, 0),
            _f(x.answer_sentiment, 2, True),
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Domain",
            "Retrieved %",
            "Cited %",
            "Cited when retrieved %",
            "C-SoV %",
            "PAWC share %",
            "First cite (sentence)",
            "Ignored when retrieved %",
            "Answer sentiment",
        ],
        rows,
    )


def deltas_md(r: dict) -> str:
    df = r["deltas"]
    rows = [
        [
            f"`{x.arm}`",
            _ci(x.d_pwc_pp, x.d_pwc_lo, x.d_pwc_hi),
            _f(x.rel_pct, 0, True) if not pd.isna(x.rel_pct) else "n/a",
            _ci(x.d_csov_pp, x.d_csov_lo, x.d_csov_hi),
            _f(x.d_cite_rate_pp, 1, True),
            _f(x.d_retrieval_pp, 1, True),
            _f(x.d_sentiment, 3, True),
            _p(x.p_holm),
            str(int(x.n_queries)),
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Arm",
            "ΔPAWC pp [95% CI]",
            "Rel Δ %",
            "ΔC-SoV pp [95% CI]",
            "Δ cited pp",
            "Δ retrieved pp",
            "Δ sentiment",
            "p (Holm)",
            "n",
        ],
        rows,
    )


def position_md(r: dict) -> str:
    df = r["position"]
    rows = [
        [
            str(int(x.position)),
            _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
            _ci(x.d_pwc_vs_first_pp, x.d_lo, x.d_hi)
            if x.position != df.position.iloc[0]
            else "ref",
            _f(x.cite_rate_pct, 0),
            _p(x.p) if x.position != df.position.iloc[0] else "",
            str(int(x.n_queries)),
        ]
        for x in df.itertuples()
    ]
    return _table(
        ["Target slot", "PAWC share % [95% CI]", "Δ vs slot 1 pp [95% CI]", "Cited %", "p", "n"],
        rows,
    )


def boost_md(r: dict) -> str:
    df = r["boost"]
    rows = [
        [
            _f(x.boost, 2),
            _f(x.retrieval_pct, 0),
            _lvl(x.pwc_pct, x.pwc_lo, x.pwc_hi),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi) if x.boost != 0 else "ref",
            _f(x.cite_rate_pct, 0),
            _p(x.p) if x.boost != 0 else "",
        ]
        for x in df.itertuples()
    ]
    return _table(
        [
            "Boost w",
            "Target retrieved %",
            "PAWC share % [95% CI]",
            "Δ vs w=0 pp [95% CI]",
            "Cited %",
            "p",
        ],
        rows,
    )


def claim_md(r: dict) -> str:
    """Plain statements of what the sweeps measured, for the 'small changes, big shifts' claim."""
    m, pos, boost, deltas = r["manifest"], r["position"], r["boost"], r["deltas"]
    out = []
    if pos is not None and len(pos) > 1:
        first, last = pos.iloc[0], pos.iloc[-1]
        ratio = f", {_f(first.pwc_pct / last.pwc_pct, 1)}x" if last.pwc_pct > 0 else ""
        delta = _ci(last.d_pwc_vs_first_pp, last.d_lo, last.d_hi)
        out.append(
            f"- Context order: with identical page content, moving the target from slot "
            f"{int(first.position)} to slot {int(last.position)} changed its PAWC share from "
            f"{_f(first.pwc_pct)}% to {_f(last.pwc_pct)}% (Δ {delta} pp{ratio}, "
            f"n={int(last.n_queries)} queries)."
        )
    if boost is not None and len(boost) > 1:
        ss = m.get("score_scale", {})
        sig = boost[(boost.boost > 0) & ((boost.d_lo > 0) | (boost.d_hi < 0))]
        smallest = sig.iloc[0] if len(sig) else None
        b1 = boost[boost.boost > 0].iloc[0]
        out.append(
            f"- Retrieval weighting: the median spread of final scores across the top 5 was "
            f"{_f(ss.get('median_top5_spread'), 3)} and the median gap between the 5th and 6th "
            f"candidate {_f(ss.get('median_gap_5_6'), 3)}. A boost of {_f(b1.boost, 2)} moved target "
            f"retrieval from {_f(boost.iloc[0].retrieval_pct, 0)}% to {_f(b1.retrieval_pct, 0)}% and PAWC "
            f"share by {_ci(b1.d_pwc_pp, b1.d_lo, b1.d_hi)} pp."
            + (
                f" The smallest boost whose CI excludes zero was {_f(smallest.boost, 2)} "
                f"({_ci(smallest.d_pwc_pp, smallest.d_lo, smallest.d_hi)} pp)."
                if smallest is not None
                else " No boost in the sweep moved PAWC share with a CI excluding zero."
            )
        )
    if deltas is not None:
        d = deltas.set_index("arm")
        if "aa_resample" in d.index:
            a = d.loc["aa_resample"]
            out.append(
                f"- Noise floor: re-sampling the unchanged prompts (A/A) moved PAWC share by "
                f"{_ci(a.d_pwc_pp, a.d_pwc_lo, a.d_pwc_hi)} pp."
            )
        if "metadata" in d.index:
            a = d.loc["metadata"]
            out.append(
                f"- Metadata only (title + description): {_ci(a.d_pwc_pp, a.d_pwc_lo, a.d_pwc_hi)} pp, "
                f"Holm p {_p(a.p_holm)}."
            )
    return "\n".join(out)


def bandit_md(r: dict) -> str:
    df = r["bandit"]
    m = r["manifest"]["config"]["bandit"]
    rows = [
        [
            x.policy,
            f"{_f(x.final_regret, 2)} ± {_f(x.final_regret_ci, 2)}",
            _f(x.mean_reward_pp, 2, True),
            f"`{x.top_arm}` ({_f(x.top_arm_share * 100, 0)}%)"
            if isinstance(x.top_arm, str) and x.top_arm
            else "",
        ]
        for x in df.itertuples()
    ]
    return (
        f"Offline replay, {m['rounds']} rounds x {m['runs']} runs; regret is in units of PAWC share "
        f"(1.0 = 100 pp) summed over rounds.\n\n"
        + _table(
            [
                "Policy",
                "Cumulative regret at T (±95% CI)",
                "Mean reward pp/round",
                "Most chosen arm",
            ],
            rows,
        )
    )


def trajectory_md(r: dict) -> str:
    df = r["trajectory"]
    rows = [
        [
            str(int(x.step)),
            f"`{x.proposed}`",
            _f(x.predicted_reward_pp, 2, True),
            _ci(x.d_pwc_pp, x.d_lo, x.d_hi),
            "kept" if x.kept else "rejected",
            f"`{x.applied}`",
            _f(x.heldout_pwc_pct),
        ]
        for x in df.itertuples()
    ]
    return (
        f"Held-out queries: {int(df.n_heldout.iloc[0])}. An arm is kept only if the lower 95% bound "
        f"on its held-out ΔPAWC is above zero.\n\n"
        + _table(
            [
                "Step",
                "Proposed",
                "Predicted pp",
                "Held-out ΔPAWC pp [95% CI]",
                "Decision",
                "Applied so far",
                "Held-out PAWC %",
            ],
            rows,
        )
    )


def summary_md(r: dict, level: int = 1) -> str:
    h = "#" * level
    parts = [f"{h} {label(r)}", header_md(r)]
    if r["domains"] is not None:
        parts += [f"{h}# Baseline visibility", domains_md(r)]
    if r["deltas"] is not None:
        parts += [f"{h}# Sandbox arms (target: {_target(r)})", deltas_md(r)]
    if r["position"] is not None:
        parts += [f"{h}# Position sweep", position_md(r)]
    if r["boost"] is not None:
        parts += [f"{h}# Boost sweep", boost_md(r)]
    claim = claim_md(r)
    if claim:
        parts += [f"{h}# What the sweeps show", claim]
    if r["bandit"] is not None:
        parts += [f"{h}# Bandit replay", bandit_md(r)]
    if r["trajectory"] is not None:
        parts += [f"{h}# Greedy optimization loop", trajectory_md(r)]
    return "\n\n".join(parts) + "\n"


def _target(r: dict) -> str:
    df = r["domains"]
    t = df[df.role == "target"].domain.tolist() if df is not None else []
    return ", ".join(t) or "target"


def write_summary(d: Path) -> Path:
    p = d / "summary.md"
    p.write_text(summary_md(load(d)))
    return p


def _order(results: list[dict]) -> list[dict]:
    return sorted(results, key=lambda r: (r["manifest"].get("llm_is_fake", False), str(r["dir"])))


def write_results(dirs: list[Path], out: Path, readme: Path | None = None) -> None:
    results = _order([load(d) for d in dirs if (d / "manifest.json").exists()])
    for r in results:
        write_summary(r["dir"])
    body = [
        "# Results",
        "Generated by `vizor report` from the directories under `experiments/results/`. "
        "Every number below is read from those files; see `experiments/README.md` for how to "
        "reproduce them.",
    ]
    body += [summary_md(r, level=2) for r in results]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n\n".join(body).rstrip() + "\n")
    if readme is not None and results:
        text = readme.read_text()
        if README_START in text and README_END in text:
            block = readme_block(results)
            text = re.sub(
                re.escape(README_START) + ".*?" + re.escape(README_END),
                lambda _: f"{README_START}\n{block}\n{README_END}",
                text,
                flags=re.S,
            )
            readme.write_text(text)


def readme_block(results: list[dict]) -> str:
    parts = []
    for r in results:
        parts.append(f"#### {label(r)}")
        parts.append(header_md(r))
        if r["deltas"] is not None:
            keep = r["deltas"]
            parts.append(deltas_md({**r, "deltas": keep}))
        if r["position"] is not None:
            parts.append(position_md(r))
        if r["boost"] is not None:
            parts.append(boost_md(r))
        claim = claim_md(r)
        if claim:
            parts.append(claim)
    return "\n\n".join(parts)
